// Auto-generated by `npm run cf-typegen` — do not commit sensitive bindings
interface CloudflareEnv {
  DB: D1Database
  KV: KVNamespace
  R2: R2Bucket
  ASSETS: Fetcher
  WORKER_SELF_REFERENCE: Fetcher
  ANTHROPIC_API_KEY: string
  SUPABASE_URL: string
  SUPABASE_ANON_KEY: string
  SUPABASE_SERVICE_ROLE_KEY: string
}
